version: '3.8'

services:
  db:
    image: mariadb
    container_name: home_assistant_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
     - db:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD  # Mot de passe de l'utilisateur root de mariadb
     - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE  # Nom de la base de données à créer à l'initialisation du conteneur
     - MYSQL_USER=$NEXTCLOUD_MYSQL_USER  # Nom de l'utilisateur de la base de données créée
     - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD  # Mot de passe de l'utilisateur créé  

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container-container_name: home_assistant
    restart: always
    volumes:
    - /PATH_TO_YOUR_CONFIG:/config
    links:
    - home_assistant_db
    environment:
     - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE  # Nom de la base de données à créer à l'initialisation du conteneur
     - MYSQL_USER=$NEXTCLOUD_MYSQL_USER  # Nom de l'utilisateur de la base de données créée
     - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD  # Mot de passe de l'utilisateur créé  

  volumes:
    /PATH_TO_YOUR_CONFIG:build:
    db:
