#Penser à créer les volumes sur votre espace de stockage :
#/backup/nextcloud/db
#/backup/nextcloud/html
#/backup/nginx/db
#/backup/nginx/data
#/backup/nginx/letsencrypt

version: '3'

services:
  dbnextcloud:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /backup/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=value  # Mot de passe de l'utilisateur root de mariadb
      - MYSQL_DATABASE=bddnextcloud  # Nom de la base de données à créer à l'initialisation du conteneur
      - MYSQL_USER=value  # Nom de l'utilisateur de la base de données créé
      - MYSQL_PASSWORD=value  # Mot de passe de l'utilisateur créé

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - dbnextcloud
    volumes:
      - /backup/nextcloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=value  # Mot de passe de l'utilisateur de mariadb créé
      - MYSQL_DATABASE=bddnextcloud  # Nom de la base de données créer à l'initialisation du conteneur
      - MYSQL_HOST=dbnextcloud  # Nom d'hôte du conteneur de la base de données créé
      - MYSQL_USER=value  # Mot de passe de l'utilisateur créé
  
  dbreverseproxy:
    image: mariadb
    container_name: home_assistant_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
     - /backup/nginx/db:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=value  # Mot de passe de l'utilisateur root de mariadb
     - MYSQL_DATABASE=bddreverseproxy  # Nom de la base de données à créer à l'initialisation du conteneur
     - MYSQL_USER=value  # Nom de l'utilisateur de la base de données créé
     - MYSQL_PASSWORD=value  # Mot de passe de l'utilisateur créé  

  reverseproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    links:
      - dbreverseproxy
    volumes:
      - /backup/nginx/data:/data
      - /backup/nginx/letsencrypt:/etc/letsencrypt
    environment:
      - MYSQL_PASSWORD=value  # Mot de passe de l'utilisateur de mariadb créé
      - MYSQL_DATABASE=bddreverseproxy  # Nom de la base de données créer à l'initialisation du conteneur
      - MYSQL_HOST=dbreverseproxy  # Nom d'hôte du conteneur de la base de données créé
      - MYSQL_USER=value  # Mot de passe de l'utilisateur créé