---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Europe/Paris
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - /opt/plex/config:/config
      - /opt/plex/films:/movies
      - /opt/plex/series:/series
      - /opt/plex/musics:/music
      - /opt/plex/onrop:/onrop
      - /opt/plex/dcmi:/images
    restart: unless-stopped
#/opt/plex/config /opt/plex/films /opt/plex/series /opt/plex/musics /opt/plex/dcmi
#port par defaut : 32400
#if error : This XML file does not appear to have any style information associated with it. The document tree is shown below --> http://ipaddress:32400/manage
