---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Europe/Paris
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - /opt/plex/config:/config
      - /opt/plex/tv:/tv
      - /opt/plex/movies:/movies
      - /opt/plex/series:/series
      - /opt/plex/music:/music
      - /opt/plex/onrop:/onrop
      - /opt/plex/images:/images
    restart: unless-stopped
