version: '3'

services:
  dbnextcloud:
    image: mariadb:latest
    container_name: db_nextcloud
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /opt/nextcloud/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "$VALUE"  # Mot de passe de l'utilisateur root de mariadb
      MYSQL_DATABASE: "$VALUE"  # Nom de la base de données à créer à l'initialisation du conteneur
      MYSQL_USER: "$VALUE"  # Nom de l'utilisateur de la base de données créée
      MYSQL_PASSWORD: "$VALUE"  # Mot de passe de l'utilisateur créé 

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    links:
      - dbnextcloud
    volumes:
      - /opt/nextcloud/html:/var/www/html
    environment:
      MYSQL_HOST: "$VALUE"
      MYSQL_USER: "$VALUE"  # Nom de l'utilisateur de la base de données créée
      MYSQL_PASSWORD: "$VALUE"  # Mot de passe de l'utilisateur créé
      MYSQL_DATABASE: "$VALUE"  # Nom de la base de données à créer à l'initialisation du conteneur
  
  reverseproxydb:
    image: mariadb:latest
    container_name: db_nginx
    restart: always
    volumes:
      - /opt/nginx/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "$VALUE"  # Mot de passe de l'utilisateur root de mariadb
      MYSQL_DATABASE: "$VALUE"  # Nom de la base de données à créer à l'initialisation du conteneur
      MYSQL_USER: "$VALUE"  # Nom de l'utilisateur de la base de données créée
      MYSQL_PASSWORD: "$VALUE"  # Mot de passe de l'utilisateur créé  

  reverseproxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: always
    ports:
      - '80:80' # ne pas modifier
      - '81:81'
      - '443:443' # ne pas modifier
    links:
      - reverseproxydb
    environment:
      DB_MYSQL_HOST: "$VALUE"
      DB_MYSQL_PORT: "$VALUE"
      DB_MYSQL_USER: "$VALUE"  # Nom de l'utilisateur de la base de données créée
      DB_MYSQL_PASSWORD: "$VALUE"  # Mot de passe de l'utilisateur créé
      DB_MYSQL_DATABASE: "$VALUE"  # Nom de la base de données à créer à l'initialisation du conteneur
    volumes:
      - /opt/nginx/data:/data
      - /opt/nginx/letsencrypt:/etc/letsencrypt
