version: '3'

services:
  dbnextcloud:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /backup/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=value
      - MYSQL_PASSWORD=value
      - MYSQL_DATABASE=value
      - MYSQL_USER=value

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - dbnextcloud
    volumes:
      - /backup/nextcloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORDvalue
      - MYSQL_DATABASEvalue
      - MYSQL_USERvalue
      - MYSQL_HOST=value
  
  reverseproxydb:
    image: mariadb
    container_name: home_assistant_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
     - /backup/nginx/db:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=value  # Mot de passe de l'utilisateur root de mariadb
     - MYSQL_DATABASE=value  # Nom de la base de données à créer à l'initialisation du conteneur
     - MYSQL_USER=value  # Nom de l'utilisateur de la base de données créée
     - MYSQL_PASSWORD=value  # Mot de passe de l'utilisateur créé  

  reverseproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    links:
      - reverseproxydb
    volumes:
      - /backup/nginx/data:/data
      - /backup/nginx/letsencrypt:/etc/letsencrypt
    environment:
      - MYSQL_ROOT_PASSWORD=value
      - MYSQL_DATABASE=value
      - MYSQL_USER=value
      - MYSQL_HOST=value
