version: '3'

services:
  dbnextcloud:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /backup/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=?????
      - MYSQL_PASSWORD=?????
      - MYSQL_DATABASE=?????
      - MYSQL_USER=?????

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - dbnextcloud
    volumes:
      - /backup/nextcloud/html:/var/www/html
    environment:
      - MYSQL_PASSWORD=?????
      - MYSQL_DATABASE=?????
      - MYSQL_USER=?????
      - MYSQL_HOST=db
  
  reverseproxydb:
    image: mariadb
    container_name: home_assistant_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
     - /backup/nginx/db:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD  # Mot de passe de l'utilisateur root de mariadb
     - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE  # Nom de la base de données à créer à l'initialisation du conteneur
     - MYSQL_USER=$NEXTCLOUD_MYSQL_USER  # Nom de l'utilisateur de la base de données créée
     - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD  # Mot de passe de l'utilisateur créé  

  reverseproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    links:
      - reverseproxydb
    volumes:
      - /backup/nginx/data:/data
      - /backup/nginx/letsencrypt:/etc/letsencrypt
